<?php
declare(strict_types=1);
date_default_timezone_set('Asia/Taipei');
session_name('HUOMANGE_ADMIN');
$sessionLifetime=86400;
ini_set('session.gc_maxlifetime',(string)$sessionLifetime);
session_set_cookie_params(['lifetime'=>$sessionLifetime,'path'=>'/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);
session_start();
if(!empty($_SESSION['admin_logged_in'])){$expiresAt=(int)($_SESSION['admin_expires_at']??0);if($expiresAt<=0){$expiresAt=time()+$sessionLifetime;$_SESSION['admin_expires_at']=$expiresAt;}if($expiresAt<=time()){$_SESSION=[];session_destroy();}else setcookie(session_name(),session_id(),['expires'=>$expiresAt,'path'=>'/','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);}
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
require_once __DIR__.'/facebook-listing-lib.php';
$dbFile=__DIR__.'/../data/shared-db.json';$publishFile=__DIR__.'/../data/facebook-publish-data.json';$scheduleKey='facebookPublishSchedules';$jobKey='facebookPublishJobs';$groupKey='facebookGroupRegistry';$brokerKey='facebookBrokerDisclosure';
function out($x,int $status=200):void{http_response_code($status);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);exit;}
function txt($x):string{return trim((string)($x??''));}function sid($x):string{return preg_replace('/[^A-Za-z0-9_-]/','',txt($x));}
function listv($x):array{if(!is_array($x))return[];$o=[];foreach($x as $v){$v=txt($v);if($v!==''&&!in_array($v,$o,true))$o[]=$v;}return$o;}
const BROKER_DISCLOSURE_LINE='經紀人：馮雋引（113）000395字號';
function brokerDisclosure():array{return['required'=>true,'line'=>BROKER_DISCLOSURE_LINE,'brokerName'=>'馮雋引','license'=>'（113）000395字號','updatedAt'=>date('c')];}
function ensureBrokerDisclosure(string $text):string{$text=trim((string)preg_replace('/\n?經紀人：.*(?:字號|[0-9]{6}).*/u','',$text));return$text."\n".BROKER_DISCLOSURE_LINE;}
function readDb():array{$d=json_decode(@file_get_contents($GLOBALS['dbFile'])?:'{}',true);if(!is_array($d))$d=[];$p=json_decode(@file_get_contents($GLOBALS['publishFile'])?:'{}',true);if(is_array($p))foreach([$GLOBALS['scheduleKey'],$GLOBALS['jobKey'],$GLOBALS['groupKey'],$GLOBALS['brokerKey']]as$key)if(array_key_exists($key,$p))$d[$key]=$p[$key];return$d;}
function writeDb(array $d):void{$existing=json_decode(@file_get_contents($GLOBALS['publishFile'])?:'{}',true);$p=is_array($existing)?$existing:[];foreach([$GLOBALS['scheduleKey'],$GLOBALS['jobKey'],$GLOBALS['groupKey']]as$key)$p[$key]=$d[$key]??[];$p[$GLOBALS['brokerKey']]=$d[$GLOBALS['brokerKey']]??brokerDisclosure();$p['updatedAt']=date('c');$json=json_encode($p,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);$tmp=$GLOBALS['publishFile'].'.tmp';if(!is_string($json)||file_put_contents($tmp,$json,LOCK_EX)===false||!rename($tmp,$GLOBALS['publishFile']))out(['ok'=>false,'message'=>'Facebook 排程資料無法寫入'],500);}
function arrDb(array $d,string $key):array{$v=$d[$key]??[];if(is_string($v))$v=json_decode($v,true);return is_array($v)?$v:[];}
function todayLockedCases(array $d):array{$today=date('Y-m-d');$locked=[];foreach(arrDb($d,$GLOBALS['jobKey'])as$j){if(in_array($j['status']??'',['cancelled','failed'],true))continue;$scheduled=substr(txt($j['scheduledAt']??''),0,10);$published=($j['status']??'')==='published'?substr(txt($j['updatedAt']??$j['scheduledAt']??''),0,10):'';if($scheduled===$today||$published===$today){$id=sid($j['caseId']??'');if($id!=='')$locked[$id]=true;}}return$locked;}
function itemsWithDailyLock(array $d):array{$locked=todayLockedCases($d);$availableOn=date('Y-m-d',strtotime('+1 day'));$rows=items($d);foreach($rows as&$x){$x['todayLocked']=isset($locked[$x['id']]);$x['availableOn']=$x['todayLocked']?$availableOn:'';}unset($x);return$rows;}
function admin():bool{return !empty($_SESSION['admin_logged_in']);}
function firstTxt(array $x,array $keys):string{foreach($keys as $k){$v=txt($x[$k]??'');if($v!=='')return$v;}return'';}
function numVal(string $v):float{return(float)preg_replace('/[^0-9.\-]/','',$v);}
function imageUrls(array $x):array{$values=[];foreach(['images','photos','photoList','gallery']as$k)if(isset($x[$k])&&is_array($x[$k]))$values=array_merge($values,$x[$k]);foreach(['image','imageUrl','img','photo','cover','thumb','thumbnail']as$k)if(isset($x[$k]))$values[]=$x[$k];$out=[];foreach($values as$v){if(is_array($v))$v=$v['url']??$v['src']??$v['imageUrl']??$v['data']??'';$v=txt($v);if(($v!==''&&(str_starts_with($v,'http://')||str_starts_with($v,'https://')||str_starts_with($v,'data:image/')))&&!in_array($v,$out,true))$out[]=$v;}return$out;}
function photoCache():array{$f=__DIR__.'/../data/facebook-photo-cache.json';$d=json_decode(@file_get_contents($f)?:'{}',true);return is_array($d)?$d:[];}
function writePhotoCache(array $d):void{$f=__DIR__.'/../data/facebook-photo-cache.json';$j=json_encode($d,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);if(!is_string($j))return;$tmp=$f.'.tmp';if(file_put_contents($tmp,$j,LOCK_EX)!==false)@rename($tmp,$f);}
function fetchListingMeta(string $url):array{if(!preg_match('~^https?://~i',$url))return[];$ctx=stream_context_create(['http'=>['timeout'=>10,'follow_location'=>1,'max_redirects'=>4,'user_agent'=>'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36','ignore_errors'=>true]]);$html=@file_get_contents($url,false,$ctx,0,900000);if(!is_string($html)||$html==='')return[];$out=[];$patterns=['~<meta[^>]+property=["\']og:image["\'][^>]+content=["\']([^"\']+)["\']~i','~<meta[^>]+content=["\']([^"\']+)["\'][^>]+property=["\']og:image["\']~i'];foreach($patterns as$re)if(preg_match($re,$html,$m)){$out['url']=html_entity_decode(trim($m[1]),ENT_QUOTES|ENT_HTML5,'UTF-8');break;}$decoded=html_entity_decode($html,ENT_QUOTES|ENT_HTML5,'UTF-8');$gallery=[];$seenKeys=[];if(preg_match_all('~https://yccdn\.yungching\.com\.tw/v1/image/\?[^"\'<>\s]+~i',$decoded,$matches))foreach($matches[0]as$image){$image=html_entity_decode($image,ENT_QUOTES|ENT_HTML5,'UTF-8');$query=[];parse_str((string)parse_url($image,PHP_URL_QUERY),$query);$key=txt($query['key']??'')?:$image;if(isset($seenKeys[$key]))continue;$seenKeys[$key]=true;$gallery[]=$image;if(count($gallery)>=10)break;}if(txt($out['url']??'')!==''&&!in_array($out['url'],$gallery,true))array_unshift($gallery,$out['url']);$out['urls']=array_slice(array_values(array_unique($gallery)),0,10);if(txt($out['url']??'')===''&&!empty($out['urls']))$out['url']=$out['urls'][0];$cities='基隆市|台北市|新北市|桃園市|新竹市|新竹縣|苗栗縣|台中市|彰化縣|南投縣|雲林縣|嘉義市|嘉義縣|台南市|高雄市|屏東縣|宜蘭縣|花蓮縣|台東縣|澎湖縣|金門縣|連江縣';if(preg_match('/('.$cities.')([一-龥]{1,5}(?:區|鎮|鄉|市))/u',$decoded,$m)){$out['city']=$m[1];$out['district']=$m[2];$out['address']=$m[1].$m[2];if(preg_match('/'.preg_quote($m[1].$m[2],'/').'([一-龥0-9之\-]{1,20}(?:路|街|段|巷|弄|號))/u',$decoded,$a))$out['address'].=$a[1];}return$out;}

function geoJson(string $url,array $http=[]):array{$defaults=['timeout'=>18,'ignore_errors'=>true,'user_agent'=>'HuowangPropertyAdmin/1.0 (+https://huowang.paohui.org/)','header'=>"Referer: https://huowang.paohui.org/\r\nAccept: application/json\r\n"];$ctx=stream_context_create(['http'=>array_merge($defaults,$http)]);$raw=@file_get_contents($url,false,$ctx);$data=json_decode(is_string($raw)?$raw:'',true);return is_array($data)?$data:[];}
function geocodeAddress(string $address):array{static $last=0.0;$wait=1.05-(microtime(true)-$last);if($wait>0)usleep((int)($wait*1000000));$url='https://nominatim.openstreetmap.org/search?'.http_build_query(['q'=>$address,'format'=>'jsonv2','limit'=>1,'countrycodes'=>'tw']);$rows=geoJson($url);$last=microtime(true);$row=is_array($rows[0]??null)?$rows[0]:[];$lat=(float)($row['lat']??0);$lon=(float)($row['lon']??0);return $lat&&$lon?['lat'=>$lat,'lon'=>$lon,'displayName'=>txt($row['display_name']??'')]:[];}
function distanceM(float $lat1,float $lon1,float $lat2,float $lon2):int{$r=6371000;$p1=deg2rad($lat1);$p2=deg2rad($lat2);$dp=deg2rad($lat2-$lat1);$dl=deg2rad($lon2-$lon1);$a=sin($dp/2)**2+cos($p1)*cos($p2)*sin($dl/2)**2;return(int)round($r*2*atan2(sqrt($a),sqrt(1-$a)));}
function fetchAmenities(float $lat,float $lon):array{$q='[out:json][timeout:15];(nwr(around:5000,'.$lat.','.$lon.')[shop=convenience];nwr(around:5000,'.$lat.','.$lon.')[shop=supermarket];nwr(around:5000,'.$lat.','.$lon.')[amenity=school];nwr(around:5000,'.$lat.','.$lon.')[amenity=hospital];nwr(around:5000,'.$lat.','.$lon.')[amenity=clinic];nwr(around:5000,'.$lat.','.$lon.')[railway=station];nwr(around:5000,'.$lat.','.$lon.')[leisure=park];);out center tags;';$data=geoJson('https://overpass-api.de/api/interpreter',['method'=>'POST','header'=>"Content-Type: application/x-www-form-urlencoded\r\nUser-Agent: HuowangPropertyAdmin/1.0 (+https://huowang.paohui.org/)\r\n",'content'=>http_build_query(['data'=>$q])]);$best=[];foreach($data['elements']??[]as$e){$tags=is_array($e['tags']??null)?$e['tags']:[];$name=txt($tags['name:zh']??$tags['name']??'');if($name===''||mb_strpos($name,'檳榔')!==false)continue;$elat=(float)($e['lat']??$e['center']['lat']??0);$elon=(float)($e['lon']??$e['center']['lon']??0);if(!$elat||!$elon)continue;$type='';$label='';if(($tags['shop']??'')==='convenience'){$type='convenience';$label='便利商店';}elseif(($tags['shop']??'')==='supermarket'){$type='supermarket';$label='超市';}elseif(($tags['amenity']??'')==='school'){$type='school';$label='學校';}elseif(in_array($tags['amenity']??'',['hospital','clinic'],true)){$type='medical';$label='醫療';}elseif(($tags['railway']??'')==='station'){$type='station';$label='車站';}elseif(($tags['leisure']??'')==='park'){$type='park';$label='公園';}if($type==='')continue;$meters=distanceM($lat,$lon,$elat,$elon);if(!isset($best[$type])||$meters<$best[$type]['meters'])$best[$type]=['type'=>$type,'label'=>$label,'name'=>$name,'meters'=>$meters];}$order=['convenience','supermarket','school','medical','station','park'];$out=[];foreach($order as$key)if(isset($best[$key]))$out[]=$best[$key];return$out;}
function distanceText(int $meters):string{return$meters<1000?$meters.' 公尺':number_format($meters/1000,1).' 公里';}
function publicSiteId(string $id):string{return str_starts_with($id,'STORE-')?'YC-'.substr($id,6):$id;}
function publicSiteItem(string $id):array{$file=__DIR__.'/../huowang/data/custom-properties.json';$store=json_decode(@file_get_contents($file)?:'{}',true);foreach($store['items']??[]as$row)if(is_array($row)&&txt($row['id']??'')===publicSiteId($id))return$row;return[];}
function syncPublicSite(array $selected):void{
  $file=__DIR__.'/../huowang/data/custom-properties.json';$store=json_decode(@file_get_contents($file)?:'{}',true);if(!is_array($store))$store=[];$rows=is_array($store['items']??null)?$store['items']:[];$map=[];foreach($rows as$row)if(is_array($row)&&txt($row['id']??'')!=='')$map[txt($row['id'])]=$row;
  foreach($selected as$x){$id=publicSiteId(txt($x['id']??''));if($id==='')continue;$title=txt($x['title']??'');$type=txt($x['type']??'');if($type==='')$type=mb_strpos($title,'農舍')!==false?'農舍':(mb_strpos($title,'土地')!==false?'土地':'住宅');$images=is_array($x['imageUrls']??null)?array_slice($x['imageUrls'],0,20):[];$map[$id]=array_merge($map[$id]??[],['id'=>$id,'title'=>$title,'titleVi'=>txt(($map[$id]['titleVi']??'')),'price'=>txt($x['price']??'')?:'洽詢','area'=>txt($x['district']??''),'areaVi'=>txt(($map[$id]['areaVi']??'')),'city'=>txt($x['city']??''),'address'=>txt($x['amenitiesAddress']??'')?:txt($x['city']??'').txt($x['district']??''),'addressVi'=>txt(($map[$id]['addressVi']??'')),'category'=>$type,'categoryVi'=>txt(($map[$id]['categoryVi']??'')),'layout'=>txt($x['layout']??'')?:'格局洽詢','land'=>txt($x['landArea']??'')?:'洽詢','build'=>txt($x['mainBuildArea']??$x['totalArea']??'')?:'洽詢','unit'=>txt($x['unitPrice']??'')?:'洽詢','image'=>$images[0]??'assets/huowang-card.jpg','images'=>$images,'amenities'=>is_array($x['amenities']??null)?$x['amenities']:[],'amenitiesAddress'=>txt($x['amenitiesAddress']??''),'sourceUrl'=>txt($x['sourceUrl']??''),'featured'=>true,'summaryZh'=>txt($x['summaryZh']??'')?:$title.'，詳細資料歡迎聯絡火旺伯。','summaryVi'=>txt(($map[$id]['summaryVi']??'')),'hidden'=>false,'updatedAt'=>date('c')]);}
  $store['items']=array_values($map);$json=json_encode($store,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);if(!is_string($json))return;$tmp=$file.'.tmp';if(file_put_contents($tmp,$json,LOCK_EX)!==false)@rename($tmp,$file);
}
function postText(array $x):string{return fb_post_text($x);}
function ensureListingAssets(array $x):array{
  $urls=$x['imageUrls']??[];$source=txt($x['sourceUrl']??'');$cache=photoCache();$key=sid($x['id']??'')?:hash('sha256',$source);$entry=is_array($cache[$key]??null)?$cache[$key]:[];$dirty=false;
  $cachedUrls=is_array($entry['urls']??null)?array_values(array_filter(array_map('txt',$entry['urls']))):[];
  $needsMeta=$source!==''&&(!$urls&&count($cachedUrls)<2||txt($x['city']??'')===''&&txt($entry['city']??'')===''||txt($x['district']??'')===''&&txt($entry['district']??'')===''||txt($entry['address']??'')==='');
  if($needsMeta){$meta=fetchListingMeta($source);if($meta){$entry=array_merge($entry,$meta,['sourceUrl'=>$source,'updatedAt'=>date('c')]);$dirty=true;$cachedUrls=is_array($entry['urls']??null)?array_values(array_filter(array_map('txt',$entry['urls']))):[];}}
  $fetchedAt=strtotime(txt($entry['amenitiesFetchedAt']??''));$amenitiesStale=!$fetchedAt||$fetchedAt<time()-2592000;
  if(txt($entry['address']??'')!==''&&$amenitiesStale){$geo=geocodeAddress(txt($entry['address']));$entry['amenitiesFetchedAt']=date('c');$entry['amenities']=[];if($geo){$entry=array_merge($entry,$geo);$entry['amenities']=fetchAmenities((float)$geo['lat'],(float)$geo['lon']);}$dirty=true;}
  if($dirty){$cache[$key]=$entry;writePhotoCache($cache);}
  if(!$urls&&$cachedUrls)$urls=$cachedUrls;if(!$urls&&txt($entry['url']??'')!=='')$urls=[txt($entry['url'])];
  if(txt($x['city']??'')===''&&txt($entry['city']??'')!=='')$x['city']=txt($entry['city']);if(txt($x['district']??'')===''&&txt($entry['district']??'')!=='')$x['district']=txt($entry['district']);
  $public=publicSiteItem(txt($x['id']??''));if(txt($x['layout']??'')===''&&txt($public['layout']??'')!=='')$x['layout']=txt($public['layout']);if(txt($x['type']??'')===''&&txt($public['category']??'')!=='')$x['type']=txt($public['category']);if(txt($x['summaryZh']??'')===''&&txt($public['summaryZh']??'')!=='')$x['summaryZh']=txt($public['summaryZh']);
  $x['imageUrls']=array_slice(array_values(array_unique($urls)),0,10);$x['businessCardUrl']='https://huowang.paohui.org/huowang/assets/huowang-card.jpg';$x['amenities']=is_array($entry['amenities']??null)?$entry['amenities']:[];$x['amenitiesAddress']=txt($entry['address']??'');
  $missing=listv($x['missingFields']??[]);if(txt($x['city']??'')!=='')$missing=array_values(array_diff($missing,['縣市']));if(txt($x['district']??'')!=='')$missing=array_values(array_diff($missing,['鄉鎮區']));if(!$x['imageUrls']&&!in_array('照片',$missing,true))$missing[]='照片';$x['missingFields']=$missing;$x['postText']=ensureBrokerDisclosure(postText($x));return$x;
}
function items(array $d):array{$out=[];$sources=[['properties','合約／自有'],['sameStoreItems','同店'],['borrowItems','異店／開發'],['peerDevelopmentItems','合作物件']];foreach($sources as [$key,$source])foreach(arrDb($d,$key) as $x){if(!is_array($x)||(!empty($x['hidden'])||($x['saleStatus']??'')==='sold'))continue;$id=firstTxt($x,['id','contractNo','publicNo','sourcePublicNo']);if($id==='')continue;$city=firstTxt($x,['city','county']);$district=firstTxt($x,['district','area','town']);$title=firstTxt($x,['title','objectName','name','caseName']);$main=firstTxt($x,['mainBuildArea','sameStoreMainBuildArea','buildingArea','buildingPing','buildArea','build']);$land=firstTxt($x,['landArea','sameStoreLandArea','landPing']);$total=firstTxt($x,['totalArea','totalPing','totalAreaQuick']);$price=firstTxt($x,['price','sameStorePrice','borrowPrice','totalPrice','salePrice','askingPrice']);$unit=firstTxt($x,['unitPrice','sameStoreUnitPrice']);if($unit===''&&numVal($price)>0){$base=numVal($main)!==0?numVal($main):(numVal($total)!==0?numVal($total):numVal($land));if($base>0)$unit=rtrim(rtrim(number_format(numVal($price)/$base,2,'.',''),'0'),'.').'萬/坪';}$areaParts=[];if($main!=='')$areaParts[]='建 '.$main.'坪';if($land!=='')$areaParts[]='地 '.$land.'坪';if(!$areaParts&&$total!=='')$areaParts[]='總 '.$total.'坪';$missing=[];if($title==='')$missing[]='案名';if($city==='')$missing[]='縣市';if($district==='')$missing[]='鄉鎮區';if(!$areaParts)$missing[]='坪數';if($price==='')$missing[]='總價';$out[$id]=['id'=>$id,'title'=>$title,'city'=>$city,'district'=>$district,'sourceCategory'=>$source,'postMode'=>txt($x['postMode']??''),'mainBuildArea'=>$main,'landArea'=>$land,'totalArea'=>$total,'areaText'=>implode(' / ',$areaParts),'price'=>$price,'unitPrice'=>$unit,'layout'=>firstTxt($x,['layout','sameStoreLayout','roomLayout']),'type'=>firstTxt($x,['type','kind','category','propertyType']),'kind'=>firstTxt($x,['kind','type','category','propertyType']),'floor'=>firstTxt($x,['floor']),'houseAge'=>firstTxt($x,['houseAge']),'summaryZh'=>txt($x['summaryZh']??$x['publicNote']??''),'adText'=>txt($x['adText']??''),'sourceUrl'=>firstTxt($x,['sourceUrl','url','listingUrl']),'imageUrls'=>imageUrls($x),'missingFields'=>$missing];}return array_values($out);}
function groupAreas(array $g):array{return listv($g['areas']??[]);}
function unclassifiedGroup(array $g):bool{$a=groupAreas($g);return !$a||in_array('未分類',$a,true);}
function overseasGroup(array $g):bool{return fb_overseas_text(txt($g['name']??'').' '.txt($g['url']??'').' '.implode(' ',groupAreas($g)));}
function groupMatchScore(array $g,array $x):int{if(overseasGroup($g)||unclassifiedGroup($g)||fb_excluded_group_name(txt($g['name']??'')))return 0;$a=groupAreas($g);$score=0;$name=txt($g['name']??'');if(in_array($x['district']??'',$a,true)||(($x['district']??'')!==''&&mb_strpos($name,$x['district'])!==false))$score+=30;if(in_array($x['city']??'',$a,true))$score+=20;if(in_array('全台',$a,true)||in_array('全國',$a,true))$score+=5;return $score;}
function groupMatchesItem(array $g,array $x):bool{return groupMatchScore($g,$x)>0;}
function groupTopicOk(array $g,array $topics):bool{if(!$topics||empty($g['topics']))return true;foreach(listv($g['topics'])as$t)foreach($topics as$q)if(mb_strpos(mb_strtolower($t),$q)!==false||mb_strpos($q,mb_strtolower($t))!==false)return true;return false;}
$d=readDb();foreach([$scheduleKey,$jobKey,$groupKey] as $k)if(!isset($d[$k]))$d[$k]=[];
if(!admin())out(['ok'=>false,'message'=>'請先登入主後台'],401);
$seed=json_decode(@file_get_contents(__DIR__.'/../data/facebook-group-registry-seed.json')?:'[]',true);if(is_array($seed)&&$seed){$groups=arrDb($d,$groupKey);$known=[];foreach($groups as $row)$known[sid($row['id']??'')]=true;$changed=false;foreach($seed as $row){$id=sid($row['id']??'');if($id!==''&&!isset($known[$id])){$groups[]=$row;$known[$id]=true;$changed=true;}}if($changed){$d[$groupKey]=json_encode($groups,JSON_UNESCAPED_UNICODE);writeDb($d);}}
$method=$_SERVER['REQUEST_METHOD']??'GET';$action=txt($_GET['action']??'');
if($method==='GET'){if($action==='dashboard'){$publish=json_decode(@file_get_contents($GLOBALS['publishFile'])?:'{}',true);out(fb_dashboard(is_array($publish)?$publish:[],$d));}if($action==='listings')out(['ok'=>true,'items'=>itemsWithDailyLock($d),'today'=>date('Y-m-d'),'tomorrow'=>date('Y-m-d',strtotime('+1 day'))]);if($action==='groups')out(['ok'=>true,'groups'=>arrDb($d,$groupKey)]);if($action==='jobs')out(['ok'=>true,'jobs'=>arrDb($d,$jobKey)]);out(['ok'=>true,'schedules'=>arrDb($d,$scheduleKey)]);}
if($method!=='POST')out(['ok'=>false,'message'=>'Method not allowed'],405);
$p=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($p))out(['ok'=>false,'message'=>'JSON格式錯誤'],400);$action=txt($p['action']??'create');
if($action==='save_group'){$name=txt($p['name']??'');$url=txt($p['url']??'');if($name===''||$url==='')out(['ok'=>false,'message'=>'社團名稱與網址必填'],400);$id=sid($p['id']??'')?:'GRP-'.date('ymd-His').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));$g=['id'=>$id,'name'=>$name,'url'=>$url,'areas'=>listv($p['areas']??[]),'topics'=>listv($p['topics']??[]),'account'=>txt($p['account']??''),'relationship'=>in_array(txt($p['relationship']??''),['owned','joined'],true)?txt($p['relationship']):'joined','dailyLimit'=>max(1,min(200,(int)($p['dailyLimit']??10))),'enabled'=>!array_key_exists('enabled',$p)||(bool)$p['enabled'],'updatedAt'=>date('c')];$groups=arrDb($d,$groupKey);$found=false;foreach($groups as &$r)if(sid($r['id']??'')===$id){$g['createdAt']=$r['createdAt']??date('c');$r=array_merge($r,$g);$found=true;break;}unset($r);if(!$found){$g['createdAt']=date('c');$groups[]=$g;}$d[$groupKey]=json_encode($groups,JSON_UNESCAPED_UNICODE);writeDb($d);out(['ok'=>true,'group'=>$g]);}
if($action==='bulk_group_enabled'){$ids=listv($p['ids']??[]);if(!$ids)out(['ok'=>false,'message'=>'沒有選到社團'],400);$enabled=(bool)($p['enabled']??false);$groups=arrDb($d,$groupKey);$updated=0;foreach($groups as &$g)if(in_array(sid($g['id']??''),$ids,true)){$g['enabled']=$enabled;$g['updatedAt']=date('c');$updated++;}unset($g);$d[$groupKey]=json_encode($groups,JSON_UNESCAPED_UNICODE);writeDb($d);out(['ok'=>true,'updated'=>$updated,'enabled'=>$enabled]);}
if($action==='delete_group'){$id=sid($p['id']??'');$groups=array_values(array_filter(arrDb($d,$groupKey),fn($x)=>sid($x['id']??'')!==$id));$d[$groupKey]=json_encode($groups,JSON_UNESCAPED_UNICODE);writeDb($d);out(['ok'=>true]);}
if($action==='cancel'){$id=sid($p['id']??'');$ss=arrDb($d,$scheduleKey);foreach($ss as &$s)if(sid($s['id']??'')===$id)$s['enabled']=false;unset($s);$js=arrDb($d,$jobKey);foreach($js as &$j)if(sid($j['scheduleId']??'')===$id&&in_array($j['status']??'', ['queued','running'],true))$j['status']='cancelled';unset($j);$d[$scheduleKey]=json_encode($ss,JSON_UNESCAPED_UNICODE);$d[$jobKey]=json_encode($js,JSON_UNESCAPED_UNICODE);writeDb($d);out(['ok'=>true]);}
if($action==='claim'){$id=sid($p['jobId']??'');$js=arrDb($d,$jobKey);foreach($js as &$j)if(sid($j['id']??'')===$id&&($j['status']??'')==='queued'){$j['status']='running';$j['updatedAt']=date('c');$d[$jobKey]=json_encode($js,JSON_UNESCAPED_UNICODE);writeDb($d);out(['ok'=>true,'job'=>$j]);}unset($j);out(['ok'=>false,'message'=>'任務不存在或已處理'],409);}
if($action==='result'){$id=sid($p['jobId']??'');$js=arrDb($d,$jobKey);foreach($js as &$j)if(sid($j['id']??'')===$id){$j['status']=in_array($p['status']??'', ['queued','running','published','pending_review','blocked','failed','cancelled'],true)?$p['status']:'failed';$j['note']=txt($p['note']??'');$j['postUrl']=txt($p['postUrl']??'');$j['updatedAt']=date('c');$d[$jobKey]=json_encode($js,JSON_UNESCAPED_UNICODE);writeDb($d);out(['ok'=>true]);}unset($j);out(['ok'=>false,'message'=>'任務不存在'],404);}
if($action==='generate_today'){$publish=json_decode(@file_get_contents($GLOBALS['publishFile'])?:'{}',true);if(!is_array($publish))$publish=[];$bundle=fb_generate_today_bundle($d,$publish,date('Y-m-d'),true);fb_write_json($GLOBALS['publishFile'],$bundle['publish'],'.bak-daily-bundle-'.date('Ymd-His'));out($bundle['result']);}
if($action==='cancel_stale'){$publish=json_decode(@file_get_contents($GLOBALS['publishFile'])?:'{}',true);if(!is_array($publish))$publish=[];$jobs=fb_rows($publish['facebookPublishJobs']??[]);$groups=fb_rows($publish['facebookGroupRegistry']??[]);$cancelled=fb_cancel_stale_jobs($jobs,date('Y-m-d'));$disabled=fb_disable_overseas_groups($groups);$publish['facebookPublishJobs']=json_encode($jobs,JSON_UNESCAPED_UNICODE);$publish['facebookGroupRegistry']=json_encode($groups,JSON_UNESCAPED_UNICODE);$publish['updatedAt']=date('c');fb_write_json($GLOBALS['publishFile'],$publish,'.bak-cancel-stale-'.date('Ymd-His'));out(['ok'=>true,'cancelled'=>$cancelled,'disabledOverseasGroups'=>$disabled,'dashboard'=>fb_dashboard($publish,$d)]);}
$name=txt($p['name']??'');
$accounts=listv($p['accounts']??[]);
$manualDest=is_array($p['destinations']??null)?array_values(array_filter($p['destinations'],fn($z)=>is_array($z)&&txt($z['name']??'')!==''&&txt($z['url']??'')!=='')):[];
$caseIds=listv($p['caseIds']??[]);
$manualGroupIds=listv($p['manualGroupIds']??[]);
$cities=listv($p['cities']??[]);$districts=listv($p['districts']??[]);$areas=listv($p['areaGroups']??[]);
$topics=array_map('mb_strtolower',listv($p['topics']??[]));
$sourceMode=txt($p['sourceMode']??'same_store_contract');
$syncPublicSite=!array_key_exists('syncPublicSite',$p)||(bool)$p['syncPublicSite'];
$allItems=items($d);$itemMap=[];foreach($allItems as$x)$itemMap[$x['id']]=$x;
if($caseIds){$filtered=[];foreach($caseIds as$id)if(isset($itemMap[$id]))$filtered[]=$itemMap[$id];}
else{$filtered=array_values(array_filter($allItems,function($x)use($cities,$districts,$topics,$sourceMode){$text=mb_strtolower(($x['title']??'').' '.($x['type']??'').' '.($x['summaryZh']??'').' '.($x['adText']??''));$areaOk=(!$cities&&!$districts)||array_filter(array_merge($cities,$districts),fn($a)=>$a!==''&&($a===($x['city']??'')||$a===($x['district']??'')));$topicOk=!$topics||array_filter($topics,fn($t)=>$t!==''&&mb_strpos($text,$t)!==false);$sourceOk=$sourceMode!=='same_store_contract'||in_array($x['sourceCategory']??'',['合約／自有','同店'],true);return$areaOk&&$topicOk&&$sourceOk;}));}
$limit=max(1,min(200,(int)($p['itemsPerDay']??50)));$groupsPerListing=max(1,min(20,(int)($p['groupsPerListing']??1)));$selected=array_slice($filtered,0,$limit);$jobs=arrDb($d,$jobKey);$lockedToday=todayLockedCases($d);$alreadyToday=[];$selected=array_values(array_filter($selected,function($x)use($lockedToday,&$alreadyToday){if(isset($lockedToday[$x['id']])){$alreadyToday[]=['id'=>$x['id'],'title'=>$x['title'],'availableOn'=>date('Y-m-d',strtotime('+1 day'))];return false;}return true;}));
$selected=array_map('ensureListingAssets',$selected);
$invalid=[];foreach($selected as$x)if(!empty($x['missingFields']))$invalid[]=['id'=>$x['id'],'title'=>$x['title'],'missingFields'=>$x['missingFields']];
$registry=arrDb($d,$groupKey);$daily=[];$today=date('Y-m-d');foreach($jobs as$j){$gid=sid($j['groupId']??'');$acc=txt($j['account']??'');$day=substr(txt($j['scheduledAt']??''),0,10);if($gid!==''&&$day===$today&&!in_array($j['status']??'',['cancelled','failed'],true))$daily[$acc.'|'.$gid]=($daily[$acc.'|'.$gid]??0)+1;}
$plan=[];$unrouted=[];$scheduleDest=[];$usedGroupIds=[];$estimated=0;
foreach($selected as$x){$rowDest=[];
  if($manualDest){foreach($manualDest as$z){$rowDest[]=['name'=>txt($z['name']??''),'url'=>txt($z['url']??''),'groupId'=>sid($z['groupId']??''),'account'=>txt($z['account']??'')?:($accounts[0]??''),'dailyLimit'=>200];}}
  else foreach($accounts as$acc){if(fb_unverified_account($acc))continue;foreach($registry as$g){if(empty($g['enabled'])||txt($g['account']??'')!==$acc||overseasGroup($g)||!groupTopicOk($g,$topics))continue;$gid=sid($g['id']??'');$isManual=in_array($gid,$manualGroupIds,true)&&unclassifiedGroup($g);if(!$isManual&&!groupMatchesItem($g,$x))continue;$dailyKey=$acc.'|'.$gid;$dailyLimit=max(1,min(200,(int)($g['dailyLimit']??10)));if(($daily[$dailyKey]??0)>=$dailyLimit)continue;$daily[$dailyKey]=($daily[$dailyKey]??0)+1;$rowDest[]=['name'=>txt($g['name']??''),'url'=>txt($g['url']??''),'groupId'=>$gid,'account'=>$acc,'dailyLimit'=>$dailyLimit,'score'=>groupMatchScore($g,$x)];}}
  if(count($rowDest)>$groupsPerListing){usort($rowDest,fn($a,$b)=>($b['score']??0)<=>($a['score']??0));$rowDest=array_slice($rowDest,0,$groupsPerListing);}
  if(!$rowDest){$unrouted[]=['id'=>$x['id'],'title'=>$x['title'],'city'=>$x['city'],'district'=>$x['district']];continue;}
  foreach($rowDest as$z){$dk=($z['account']??'').'|'.($z['url']??'');$scheduleDest[$dk]=$z;if(($z['groupId']??'')!=='')$usedGroupIds[$z['groupId']]=true;}$estimated+=count($rowDest);$plan[]=['listing'=>$x,'destinations'=>$rowDest];
}
if($action==='preview')out(['ok'=>true,'brokerDisclosure'=>brokerDisclosure(),'matchedListings'=>count($selected),'estimatedJobs'=>$estimated,'alreadyScheduledToday'=>$alreadyToday,'invalidListings'=>$invalid,'unroutedListings'=>$unrouted,'listings'=>array_map(fn($x)=>['id'=>$x['id'],'title'=>$x['title'],'city'=>$x['city'],'district'=>$x['district'],'sourceCategory'=>$x['sourceCategory'],'areaText'=>$x['areaText'],'price'=>$x['price'],'unitPrice'=>$x['unitPrice'],'imageUrls'=>$x['imageUrls'],'businessCardUrl'=>$x['businessCardUrl'],'postText'=>ensureBrokerDisclosure($x['postText']??''),'missingFields'=>$x['missingFields']],$selected),'routes'=>array_map(fn($r)=>['id'=>$r['listing']['id'],'destinationCount'=>count($r['destinations'])],$plan)]);
if(empty($p['approvedPreview']))out(['ok'=>false,'message'=>'請先預覽並勾選「已確認照片與排版」'],400);
if($name===''||!$accounts)out(['ok'=>false,'message'=>'請填排程名稱與發布帳號'],400);
if(!$selected)out(['ok'=>false,'message'=>'沒有選到可排程的物件'],400);
if($invalid)out(['ok'=>false,'message'=>'物件缺少必要欄位，請先補齊縣市、鄉鎮區、坪數與總價','invalidListings'=>$invalid],400);
if($unrouted)out(['ok'=>false,'message'=>'部分物件沒有符合縣市的社團，請先分類社團或手動選擇未分類社團','unroutedListings'=>$unrouted],400);
$start=txt($p['startTime']??'09:00');$interval=max(5,min(1440,(int)($p['intervalMinutes']??15)));$sid='SCH-'.date('ymd-His').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));$created=date('c');$postType=(($p['postType']??'出售文')==='出租文'?'出租文':'出售文');
$schedule=['id'=>$sid,'name'=>$name,'enabled'=>true,'itemsPerDay'=>$limit,'groupsPerListing'=>$groupsPerListing,'startTime'=>$start,'intervalMinutes'=>$interval,'accounts'=>$accounts,'destinations'=>array_values($scheduleDest),'groupIds'=>array_keys($usedGroupIds),'manualGroupIds'=>$manualGroupIds,'selectedCaseIds'=>array_column($selected,'id'),'cities'=>$cities,'districts'=>$districts,'areaGroups'=>$areas,'topics'=>$topics,'sourceMode'=>$sourceMode,'postType'=>$postType,'syncPublicSite'=>$syncPublicSite,'matchedListings'=>count($selected),'brokerDisclosure'=>brokerDisclosure(),'approvedPreview'=>true,'approvedAt'=>$created,'createdAt'=>$created,'updatedAt'=>$created];
$existing=[];foreach($jobs as$j){if(in_array($j['status']??'',['cancelled','failed'],true))continue;$existing[substr(txt($j['scheduledAt']??''),0,10).'|'.($j['caseId']??'').'|'.($j['destinationUrl']??'').'|'.($j['account']??'')]=true;}$n=0;
foreach($plan as$row){$x=$row['listing'];foreach($row['destinations']as$z){$acc=txt($z['account']??'')?:$accounts[0];$run=strtotime(date('Y-m-d').' '.$start)+$n*$interval*60;$key=date('Y-m-d',$run).'|'.$x['id'].'|'.($z['url']??'').'|'.$acc;if(isset($existing[$key]))continue;$jobs[]=['id'=>'JOB-'.date('ymd-His',$run).'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6)),'scheduleId'=>$sid,'caseId'=>$x['id'],'title'=>$x['title'],'sourceCategory'=>$x['sourceCategory'],'city'=>$x['city'],'district'=>$x['district'],'areaText'=>$x['areaText'],'mainBuildArea'=>$x['mainBuildArea'],'landArea'=>$x['landArea'],'totalArea'=>$x['totalArea'],'price'=>$x['price'],'unitPrice'=>$x['unitPrice'],'layout'=>$x['layout'],'imageUrls'=>$x['imageUrls'],'businessCardUrl'=>$x['businessCardUrl'],'postText'=>ensureBrokerDisclosure($x['postText']??''),'brokerDisclosureLine'=>BROKER_DISCLOSURE_LINE,'postType'=>$postType,'account'=>$acc,'groupId'=>$z['groupId']??'','destinationName'=>$z['name']??'','destinationUrl'=>$z['url']??'','scheduledAt'=>date('c',$run),'status'=>'queued','postUrl'=>'','note'=>'','createdAt'=>$created];$existing[$key]=true;$n++;}}
$ss=arrDb($d,$scheduleKey);$ss[]=$schedule;$d[$scheduleKey]=json_encode($ss,JSON_UNESCAPED_UNICODE);$d[$jobKey]=json_encode($jobs,JSON_UNESCAPED_UNICODE);$d[$brokerKey]=brokerDisclosure();writeDb($d);if($syncPublicSite)syncPublicSite($selected);out(['ok'=>true,'schedule'=>$schedule,'brokerDisclosure'=>brokerDisclosure(),'matchedListings'=>count($selected),'createdJobs'=>$n,'syncedPublicSite'=>$syncPublicSite]);
?>
